[package]
name = "git-graph"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde-wasm-bindgen = "0.4.3"
wasm-bindgen = "0.2.82"
